### PR TITLE
Conference Scheduler Optimisation

### PR DESCRIPTION
**Pull request by at-robins**
Some cosmetical changes have been applied. Additionally functionality for loading conference schedule event related abstracts has been added.

### CODE REVIEW

**Comment by at-robins** [comment]
Should the abstract information for conference schedule events be displayed in a way similar to the abstract view with all the detailed information or should just the plain abstract text be shown?

**Comment by cgars** [comment]
text and a link to the abstract would be great

**Comment by at-robins** [comment]
Displaying the abstract is done, however the current design is quite ugly.
The tests failing is due to issues in the current master branch and unspecific to the commited changes.

**Comment by at-robins** [comment]
Added a previously missed error handling commit. The design of the abstract display has also been slightly improved; it still does not look too good however.

**Pull request merged**
